CREATE TABLE `quiz_question` ( `id` INT(11) NOT NULL AUTO_INCREMENT , `quiz_group_id` INT(11) NOT NULL ,  `question` TEXT NOT NULL , `option1` VARCHAR(191) NOT NULL , `option2` VARCHAR(191) NOT NULL , `option3` VARCHAR(191) NULL DEFAULT NULL , `option4` VARCHAR(191) NULL DEFAULT NULL , `option5` VARCHAR(191) NULL DEFAULT NULL , `option6` VARCHAR(191) NULL DEFAULT NULL ,`answer` VARCHAR(191) NULL DEFAULT NULL , `created_at` TIMESTAMP NULL DEFAULT NULL , `updated_at` TIMESTAMP NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;


CREATE TABLE `quiz_group` ( `id` INT(11) NOT NULL AUTO_INCREMENT , `speciality_masters_id` INT(11) NOT NULL , `title` VARCHAR(191) NOT NULL , `image` VARCHAR(191) NULL DEFAULT NULL , `page` VARCHAR(191) NOT NULL , `description` TEXT NULL DEFAULT NULL , `created_at` TIMESTAMP NULL DEFAULT NULL , `updated_at` TIMESTAMP NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB

